medikit/urls.py
from django.urls import path, include

from . import views

app_name = 'medikit'

urlpatterns = [
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/kits/', views.edit_kits, name='edit_kits'),
    path('edit/kits/<int:kit_id>/', views.edit_kit, name='edit_kit'),
    path('edit/medications/', views.edit_medications, name='edit_medications'),
    path('edit/medications/<int:medication_id>/', views.edit_medication, name='edit_medication'),
    path('remove/kit/<int:kit_id>/', views.remove_kit, name='remove_kit'),
    path('remove/medication/<int:medication_id>/', views.remove_medication, name='remove_medication'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('medikit.urls')),
    path('admin/', admin.site.urls),
]

medikit/models.py
import datetime

from django.conf import settings
from django.db import models
from pytils.translit import slugify


class Kit(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='kits',
    )

    class Meta:
        unique_together = ['name', 'user']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Medication(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True)
    expiration_date = models.DateField(blank=True, null=True)
    keep_in_cold = models.BooleanField(default=False)
    do_not_freeze = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    kit = models.ForeignKey(
        Kit,
        on_delete=models.CASCADE,
        related_name='medications',
    )

    def __str__(self) -> str:
        return self.name

    @property
    def expired(self) -> bool:
        return (self.expiration_date - datetime.date.today()).days < 0

    @property
    def expires_in(self) -> datetime.timedelta:
        return self.expiration_date - datetime.date.today()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

medikit/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Kit, Medication


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match')

        return cd['password']


class AddKitForm(forms.ModelForm):
    class Meta:
        model = Kit
        fields = ('name', 'description')


class AddMedicationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None) or kwargs['instance'].kit.user
        super(AddMedicationForm, self).__init__(*args, **kwargs)
        self.fields['kit'].queryset = Kit.objects.filter(
            user__id=user.id
        ).order_by(
            'name'
        )

    class Meta:
        model = Medication
        fields = (
            'name',
            'description',
            'expiration_date',
            'keep_in_cold',
            'do_not_freeze',
            'kit',
        )
        widgets = {
            'expiration_date': forms.SelectDateWidget,
        }

medikit/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from .forms import AddKitForm, AddMedicationForm, UserRegistrationForm
from .models import Kit, Medication
from .utils import create_example_stuff

DEFAULT_KIT_NAME = 'Without kit'


def home(request):
    if request.user.is_authenticated:
        context = {
            'kits': Kit.objects.filter(
                user=request.user
            ).exclude(
                name=DEFAULT_KIT_NAME
            ).order_by(
                'name'
            ),
            'default_kit': Kit.objects.get(
                name=DEFAULT_KIT_NAME,
                user=request.user,
            )
        }
        return render(request, 'medikit/dashboard.html', context)
    else:
        return render(request, 'medikit/welcome.html', {})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()

            Kit.objects.create(name=DEFAULT_KIT_NAME, user=new_user)
            create_example_stuff(new_user)

            return render(request, 'medikit/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()

    return render(request, 'medikit/register.html', {'user_form': user_form})


@login_required
def edit_kits(request):
    if request.method == 'POST':
        form = AddKitForm(data=request.POST)
        if form.is_valid():
            new_kit = form.save(commit=False)
            new_kit.user = request.user
            new_kit.save()
            return redirect('medikit:edit_kits')
    else:
        form = AddKitForm()

    items = Kit.objects.filter(
        user=request.user
    ).exclude(
        name=DEFAULT_KIT_NAME
    ).order_by(
        'name'
    )

    context = {
        'form': form,
        'items': items,
    }

    return render(request, 'medikit/edit_kits.html', context)


@login_required
def edit_kit(request, kit_id):
    kit = get_object_or_404(Kit, id=kit_id)

    default_kit = Kit.objects.get(
        name=DEFAULT_KIT_NAME,
        user=request.user,
    )

    # TODO create a decorator
    if kit.user != request.user or kit == default_kit:
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = AddKitForm(instance=kit, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('medikit:edit_kits')
    else:
        form = AddKitForm(instance=kit)

    context = {
        'form': form,
    }

    return render(request, 'medikit/edit_kit.html', context)


@login_required
def remove_kit(request, kit_id):
    kit = get_object_or_404(Kit, id=kit_id)

    default_kit = Kit.objects.get(
        name=DEFAULT_KIT_NAME,
        user=request.user,
    )

    # TODO create a decorator
    if kit.user != request.user or kit == default_kit:
        return HttpResponseForbidden()

    kit.delete()

    return redirect('medikit:edit_kits')


@login_required
def edit_medications(request):
    if request.method == 'POST':
        form = AddMedicationForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('medikit:edit_medications')
    else:
        form = AddMedicationForm(user=request.user)

    kits = Kit.objects.filter(
        user=request.user
    ).exclude(
        name=DEFAULT_KIT_NAME
    ).order_by(
        'name'
    )

    default_kit = Kit.objects.get(
        name=DEFAULT_KIT_NAME,
        user=request.user,
    )

    context = {
        'form': form,
        'kits': kits,
        'default_kit': default_kit,
    }

    return render(request, 'medikit/edit_medications.html', context)


@login_required
def edit_medication(request, medication_id):
    medication = get_object_or_404(Medication, id=medication_id)

    # TODO create a decorator
    if medication.kit.user != request.user:
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = AddMedicationForm(instance=medication, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('medikit:edit_medications')
    else:
        form = AddMedicationForm(instance=medication)

    context = {
        'form': form,
    }

    return render(request, 'medikit/edit_medication.html', context)


@login_required
def remove_medication(request, medication_id):
    medication = get_object_or_404(Medication, id=medication_id)

    # TODO create a decorator
    if medication.kit.user != request.user:
        return HttpResponseForbidden()

    medication.delete()

    return redirect('medikit:edit_medications')

medikit/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Medikit</title>
  <link rel="stylesheet" href="{% static 'medikit/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'medikit/css/index.css' %}">
  <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
</head>
<body>
<div id="header-logo">
{#  <span class="fas fa-medkit"></span>#}
</div>
<div id="header-controls">
    <a href="{% url 'medikit:home' %}" class="btn btn-outline-primary" role="button">Home</a>
    <a href="{% url 'medikit:edit_kits' %}" class="btn btn-outline-secondary" role="button">Edit kits</a>
    <a href="{% url 'medikit:edit_medications' %}" class="btn btn-outline-secondary" role="button">Edit medications</a>
    {% if request.user.is_anonymous %}
      <a href="{% url 'medikit:login' %}" class="btn btn-outline-danger" role="button">Login</a>
    {% else %}
      <a href="{% url 'medikit:logout' %}" class="btn btn-outline-danger" role="button">Logout</a>
    {% endif %}
</div>

<div id="main">
  <div id="main-kits">
    {% block main-kits %}
    {% endblock %}
  </div>

  <div id="main-medications">
    {% block main-medications %}
    {% endblock %}
  </div>
</div>

<script src="{% static "medikit/js/jquery-3.4.1.min.js" %}"></script>
<script src="{% static "medikit/js/bootstrap.min.js" %}"></script>

{% block js_scripts %}
{% endblock %}

</body>
</html>

medikit/templates/medikit/dash-med-item.html
<div class="medication-card">
  <div class="medication-name">{{ medication.name }}</div>
  {% if medication.do_not_freeze %}
    <div class="medication-do-not-freeze" title="Do not freeze"><span class="far fa-sun"></span></div>
  {% endif %}
  {% if medication.keep_in_cold %}
    <div class="medication-keep-in-cold" title="Keep in cold"><span class="far fa-snowflake"></span></div>
  {% endif %}
  {% if medication.description %}
    <div class="medication-description">{{ medication.description }}</div>
  {% endif %}
  {% if medication.expiration_date %}
    <div class="medication-expiration-date" title="Expiration date">{{ medication.expiration_date }}</div>
  {% else %}
    <div class="medication-no-expiration-date">No expiration date</div>
  {% endif %}
</div>

medikit/templates/medikit/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block main-kits %}
  {% include 'medikit/kits-list.html' %}
{% endblock %}

{% block main-medications %}
  <div class="tab-content" id="v-pills-tabContent">
    {% for kit in kits %}
      <div class="tab-pane fade show"
           id="v-pills-{{ kit.slug }}"
           role="tabpanel"
           aria-labelledby="v-pills-{{ kit.slug }}-tab">
        {% for medication in kit.medications.all %}
          {% include 'medikit/dash-med-item.html' %}
        {% endfor %}
      </div>
    {% endfor %}
    {% if default_kit.medications.all %}
      <div class="tab-pane fade show"
           id="v-pills-{{ default_kit.slug }}"
           role="tabpanel"
           aria-labelledby="v-pills-{{ default_kit.slug }}-tab">
        {% for medication in default_kit.medications.all %}
          {% include 'medikit/dash-med-item.html' %}
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock %}

<div id="footer">footer</div>

{% block js_scripts %}
  <script src="{% static "medikit/js/index.js" %}"></script>
{% endblock %}

medikit/templates/medikit/edit_kit.html
{% extends "base.html" %}
{% block main-medications %}
  <h3>Edit kit</h3>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save kit"></p>
  </form>
{% endblock %}

medikit/templates/medikit/edit_kits.html
{% extends "base.html" %}
{% block main-medications %}
  <h3>Add new kits</h3>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add kit"></p>
  </form>
  {% for item in items %}
    <div>
      <ul>
        <li>
          {{ item.name }}
          <a href="{% url 'medikit:edit_kit' item.id %}" class="btn btn-warning" role="button">Edit</a>
          <a href="{% url 'medikit:remove_kit' item.id %}" class="btn btn-danger" role="button">Remove</a>
        </li>
      </ul>
    </div>
  {% endfor %}
{% endblock %}

medikit/templates/medikit/edit_medication.html
{% extends "base.html" %}
{% block main-medications %}
  <h3>Edit medication</h3>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save medication"></p>
  </form>
{% endblock %}

medikit/templates/medikit/edit_medications.html
{% extends "base.html" %}
{% block main-medications %}
  <h3>Add new medication</h3>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add medication"></p>
  </form>
  {% for kit in kits %}
    <h4>{{ kit.name }}</h4>
    <hr>
    {% for item in kit.medications.all %}
      <div>
        <ul>
          <li>{{ item.name }}
            <a href="{% url 'medikit:edit_medication' item.id %}" class="btn btn-warning" role="button">Edit</a>
            <a href="{% url 'medikit:remove_medication' item.id %}" class="btn btn-danger" role="button">Remove</a>
          </li>
        </ul>
      </div>
    {% endfor %}
    <br>
  {% endfor %}
  {% if default_kit.medications.all %}
    <h4>{{ default_kit.name }}</h4>
    <hr>
    {% for item in default_kit.medications.all %}
      <div>
        <ul>
          <li>{{ item.name }}
            <a href="{% url 'medikit:edit_medication' item.id %}" class="btn btn-warning" role="button">Edit</a>
            <a href="{% url 'medikit:remove_medication' item.id %}" class="btn btn-danger" role="button">Remove</a>
          </li>
        </ul>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

medikit/templates/medikit/home.html
{% extends "base.html" %}
{% load static %}
{% block main-kits %}
  {% include 'medikit/kits-list.html' %}
{% endblock %}

{% block main-drugs %}
  <div class="tab-content" id="v-pills-tabContent">
    {% for kit in kits %}
      <div class="tab-pane fade show"
           id="v-pills-{{ kit.slug }}"
           role="tabpanel"
           aria-labelledby="v-pills-{{ kit.slug }}-tab">
        {% for drug in kit.drugs.all %}
          <h4>{{ drug.name }}</h4>
          <p>Description: {{ drug.description }}</p>
          {% if drug.expired %}
            <p>Expires: <span class="expired-label">EXPIRED</span> {{ drug.expiration_date }}</p>
          {% else %}
            <p>Expires: {{ drug.expiration_date }}</p>
          {% endif %}
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

<div id="footer">footer</div>

{% block js_scripts %}
  <script src="{% static "medikit/js/index.js" %}"></script>
{% endblock %}

medikit/templates/medikit/index.html
{% extends "medikit/base.html" %}
{% load static %}
{% block main-kits %}
  {% include 'medikit/kits-list.html' %}
{% endblock %}

{% block main-drugs %}
  <div class="tab-content" id="v-pills-tabContent">
    {% for kit in kits %}
      <div class="tab-pane fade show"
           id="v-pills-{{ kit.slug }}"
           role="tabpanel"
           aria-labelledby="v-pills-{{ kit.slug }}-tab">
        {% for drug in kit.drugs.all %}
          <h4>{{ drug.name }}</h4>
          <p>Description: {{ drug.description }}</p>
          {% if drug.expired %}
            <p>Expires: <span class="expired-label">EXPIRED</span> {{ drug.expiration_date }}</p>
          {% else %}
            <p>Expires: {{ drug.expiration_date }}</p>
          {% endif %}
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

<div id="footer">footer</div>

{% block js_scripts %}
  <script src="{% static "medikit/js/index.js" %}"></script>
{% endblock %}

medikit/templates/medikit/kits-list.html
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  {% for kit in kits %}
    <a class="nav-link"
       id="v-pills-{{ kit.slug }}-tab"
       data-toggle="pill"
       href="#v-pills-{{ kit.slug }}"
       role="tab"
       aria-controls="v-pills-{{ kit.slug }}"
       aria-selected="true">
      {{ kit.name }}
    </a>
  {% endfor %}
  {% if default_kit.medications.all %}
    <a class="nav-link"
       id="v-pills-{{ default_kit.slug }}-tab"
       data-toggle="pill"
       href="#v-pills-{{ default_kit.slug }}"
       role="tab"
       aria-controls="v-pills-{{ default_kit.slug }}"
       aria-selected="true">
      {{ default_kit.name }}
    </a>
  {% endif %}
</div>

medikit/templates/medikit/register.html
{% extends "base.html" %}
{% block main-medications %}
  <h1>Create an account</h1>
  <p>Please, sign up using the following form:</p>
  <form action="." method="post">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account"></p>
  </form>
{% endblock %}

medikit/templates/medikit/register_done.html
{% extends "base.html" %}
{% block main-medications %}
  <h1>Welcome {{ new_user.first_name }}!</h1>
  <p>Your account has been successfully created. Now you can <a href="{% url "medikit:login" %}">log in</a>.</p>
{% endblock %}

medikit/templates/medikit/welcome.html
{% extends 'base.html' %}

{% block main-medications %}
  <h3>Hello everybody!</h3>
  <p>You can login <a href="{% url 'medikit:login' %}">here</a></p>
  <p>If you are new, you can register <a href="{% url 'medikit:register' %}">here</a></p>

{% endblock %}